// Transcribed from Profile_YusufSugiyarto.pdf, pages 5–6.
export const welcomeLetter = [
  "Pertama, izinkan saya melalui tulisan ini menyampaikan niatan untuk melanjutkan perjuangan akang dan teteh sekalian. Perjuangan atas masalah yang hari ini mencapai titik kulminasinya, disparitas ekonomi, teknologi, dan pengetahuan yang sudah menjadi bottleneck kemajuan peradaban. Sebagaimana akang dan teteh pahami bersama, HMI adalah organisasi candradimuka sekaligus pelopor perubahan yang ikut menentukan arah peradaban. Karena itu, jika hari ini saya menyampaikan niatan untuk mengemban amanah sebagai Ketua Umum Pengurus Besar Himpunan Mahasiswa Islam, sesungguhnya bukan semata-mata perjuangan sendiri, bukan pula tentang pergantian kepemimpinan tahunan, itu merupakan bagian dari mata rantai perjuangan panjang yang telah dirintis para pendahulu, dilanjutkan oleh akang dan teteh, lalu sampailah pada generasi kami. Sebab sejarah merupakan hasil dari mata rantai perjuangan yang diteruskan dari satu generasi ke generasi, oleh kader-kader yang mengutamakan cita-cita bersama daripada cita-cita individu.",
  "Tidak tanpa sebab seorang alumni Telkom University mengikhtiarkan amanah ini. Kampus Telkom University tumbuh dengan tradisi akademik yang menempatkan inovasi, kolaborasi, dan pemanfaatan teknologi sebagai fondasi. Di tengah percepatan transformasi digital, kampus ini tidak hanya melahirkan lulusan yang menguasai ilmu pengetahuan dan teknologi, tetapi membentuk cara berpikir yang adaptif, solutif, serta berorientasi pada kemajuan peradaban. Nilai-nilai itu saya yakini memiliki titik temu dengan ruh perjuangan HMI. Era ketika teknologi mengubah hampir seluruh sendi kehidupan, HMI memerlukan kader-kader yang mampu menjembatani idealisme dengan inovasi, menghubungkan nilai dengan solusi, serta menerjemahkan ilmu menjadi pengabdian bagi umat dan bangsa.",
  "Saya memandang amanah ini bukan hanya sebagai ikhtiar pribadi, melainkan juga kesempatan untuk menunjukkan bahwa alumni Telkom University dapat mengambil peran dalam kepemimpinan nasional. Saya berharap nilai-nilai yang ditanamkan almamater seperti inovasi dan kolaborasi dapat berkontribusi nyata dalam memperkuat HMI sebagai organisasi yang relevan dan mampu menjawab tantangan. Arnold Toynbee dalam A Study of History mengingatkan bahwa peradaban tidak runtuh karena besarnya tantangan, tetapi karena kegagalan menjawab tantangan tersebut. Peradaban bergerak ketika sekelompok kecil manusia mampu melahirkan gagasan baru bagi persoalan zamannya. Kelompok itu ia sebut sebagai creative minority. Mereka tidak selalu hadir sebagai kelompok terbesar atau paling berkuasa. Sejarah justru mengingat mereka yang memiliki keberanian berpikir, keluasan ilmu, dan kemampuan menggerakkan kesadaran masyarakat.",
  "Modernitas bukanlah ancaman bagi HMI. Modernitas adalah ruang baru bagi nilai-nilai perjuangan untuk menemukan bentuk pengabdiannya. Menjadi organisasi modern bukan berarti meninggalkan identitas, melainkan menghadirkan identitas itu melalui tata kelola yang profesional, kepemimpinan yang meritokratis, kaderisasi yang adaptif, pemanfaatan ilmu pengetahuan dan teknologi, serta jejaring nasional dan global yang semakin kuat. Sebab ukuran keberhasilan HMI bukan sekadar banyaknya kader yang menduduki jabatan, melainkan sejauh mana pemikiran, gagasan, dan nilai perjuangannya mampu memengaruhi arah kebijakan publik dan pembangunan bangsa.",
  "Atas dasar keyakinan itulah saya menyampaikan niatan ini. Bukan untuk memulai perjuangan yang baru, melainkan melanjutkan perjuangan yang telah diwariskan oleh para pendahulu. Saya meyakini bahwa setiap zaman memiliki persoalannya sendiri, dan karena itu setiap generasi memiliki tanggung jawab atas sejarahnya sendiri. Amanah generasi hari ini bukan sekadar menjaga HMI tetap hidup, tetapi memastikan HMI tetap relevan sebagai kekuatan intelektual, moral, dan sosial yang mampu menjawab tantangan zaman. Pada akhirnya, sebagaimana tujuan-tujuan baik yang senantiasa Akang dan Teteh sekalian ikhtiarkan bersama, modernitas bukanlah tujuan akhir. Jabatan bukan pula tujuan akhir. Seluruh ikhtiar ini hanyalah wasilah untuk menghadirkan cita-cita yang sejak awal diperjuangkan, yakni terwujudnya masyarakat adil makmur yang diridhai Allah SWT.",
  "Sejarah digerakkan oleh mereka yang bersungguh-sungguh menunaikan tanggung jawab zamannya. Dan sebagaimana janji Allah dalam QS. Al-’Ankabut ayat 69, jalan perjuangan itu akan selalu dibukakan bagi mereka yang terus berjalan di atasnya.",
  "Akhir kata, dengan penuh hormat saya Yusuf Sugiyarto memohon doa dan dukungan dari keluarga besar alumni Telkom University. Almamater telah membentuk cara berpikir, karakter, dan semangat untuk terus berinovasi serta memberi manfaat bagi masyarakat. Kini, melalui ikhtiar ini, saya berharap dapat membawa nama baik Telkom University dalam ruang pengabdian yang lebih luas. Semoga langkah ini menjadi bagian dari kontribusi bersama untuk mengharumkan almamater melalui partisipasi kebangsaan, memperlihatkan bahwa alumni Telkom University mampu hadir sebagai pemimpin yang tidak hanya unggul dalam bidang, tetapi juga berkomitmen membangun umat, bangsa, dan negara.",
];
